In [ ]:
##Import Libraries
import pandas as pd
import string 
import re
import nltk
from nltk.tokenize import word_tokenize
import pickle 

In [ ]:
!gdown --id 1ocv9n_G3ltsmdnYDMHGPnko3-IXAwAxU

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1ocv9n_G3ltsmdnYDMHGPnko3-IXAwAxU
To: /content/baliwisata.csv
100% 33.7k/33.7k [00:00<00:00, 18.9MB/s]


In [ ]:
dataset=pd.read_csv("baliwisata.csv")
dataset.head()

category                                             tags  \
0  ['Agrowisata']   Agrowisata, Gianyar, Dekat dari Bandara, Mahal   
1  ['Agrowisata']  Agrowisata, Gianyar, Sedang dari Bandara, Mahal   
2  ['Agrowisata']  Agrowisata, Denpasar, Dekat dari Bandara, Murah   
3  ['Agrowisata']  Agrowisata, Gianyar, Dekat dari Bandara, Gratis   
4  ['Agrowisata']  Agrowisata, Tabanan, Sedang dari Bandara, Murah   

   weekend_price  weekday_price distance  rating            place_name  \
0          50000          50000    dekat     3.0     Agrowisata Satria   
1         300000         300000   sedang     5.0      Aloha Ubud Swing   
2          35000          30000    dekat     4.0     Big Garden Corner   
3              0              0    dekat     4.5   Campuhan Ridge Walk   
4          40000          40000   sedang     4.5  Jatiluwih Green Land   

       city                                              image  \
0   Gianyar  https://drive.google.com/file/d/108VxoEhKsyV2_...   
1   Gianyar  https://drive.google.com/file/d/1bvzte6xbyb6Ey...   
2  Denpasar  https://drive.google.com/file/d/12UMKldf_s7zGI...   
3   Gianyar  https://drive.google.com/file/d/1eVpiUN3lv1uzV...   
4   Tabanan  https://drive.google.com/file/d/1vX9x5gLEmQKdg...   

                                         description  
0  ['Agrowisata Satria menawarkan 'rasa' Bali pad...  
1  ['Ajaklah orang-orang tercinta untuk mencoba a...  
2  ['Objek wisata Big Garden Corner Sanur adalah ...  
3  ['Campuhan Ridge Walk adalah sebuah trek joggi...  
4  ['Nominasi untuk penunjukan sebagai situs Wari...

In [ ]:
dataset.shape

(75, 10)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   category       75 non-null     object 
 1   tags           75 non-null     object 
 2   weekend_price  75 non-null     int64  
 3   weekday_price  75 non-null     int64  
 4   distance       75 non-null     object 
 5   rating         75 non-null     float64
 6   place_name     75 non-null     object 
 7   city           75 non-null     object 
 8   image          75 non-null     object 
 9   description    75 non-null     object 
dtypes: float64(1), int64(2), object(7)
memory usage: 6.0+ KB


# Pre-Processing

## Case Folding

In [ ]:
# lower category
cat = dataset.category.str.lower()

print('Case Folding Result : \n')
print(cat.head())
print('\n\n\n')

Case Folding Result : 

0    ['agrowisata']
1    ['agrowisata']
2    ['agrowisata']
3    ['agrowisata']
4    ['agrowisata']
Name: category, dtype: object






In [ ]:
# lower tags
tag = dataset.tags.str.lower()

print('Case Folding Result : \n')
print(tag.head())
print('\n\n\n')

Case Folding Result : 

0     agrowisata, gianyar, dekat dari bandara, mahal
1    agrowisata, gianyar, sedang dari bandara, mahal
2    agrowisata, denpasar, dekat dari bandara, murah
3    agrowisata, gianyar, dekat dari bandara, gratis
4    agrowisata, tabanan, sedang dari bandara, murah
Name: tags, dtype: object






In [ ]:
# lower description
desc = dataset.description.str.lower()

print('Case Folding Result : \n')
print(desc.head())
print('\n\n\n')

Case Folding Result : 

0    ['agrowisata satria menawarkan 'rasa' bali pad...
1    ['ajaklah orang-orang tercinta untuk mencoba a...
2    ['objek wisata big garden corner sanur adalah ...
3    ['campuhan ridge walk adalah sebuah trek joggi...
4    ['nominasi untuk penunjukan sebagai situs wari...
Name: description, dtype: object






##Remove Character

In [ ]:
#Remove Character Ingredients
cat = dataset.category.apply(str)

def remove_character(data):
    return re.sub(r"'", "", data)

cat = cat.apply(remove_character)

def listToStringWithoutBrackets(data):
    return str(data).replace('[','').replace(']','')

cat = cat.apply(listToStringWithoutBrackets)

print(cat)

0     Agrowisata
1     Agrowisata
2     Agrowisata
3     Agrowisata
4     Agrowisata
         ...    
70      Religius
71      Religius
72      Religius
73      Religius
74      Religius
Name: category, Length: 75, dtype: object


In [ ]:
tag = dataset.tags.apply(str)

def remove_character(data):
    return re.sub(r"'", "", data)

tag = tag.apply(remove_character)
print(tag)

0      Agrowisata, Gianyar, Dekat dari Bandara, Mahal
1     Agrowisata, Gianyar, Sedang dari Bandara, Mahal
2     Agrowisata, Denpasar, Dekat dari Bandara, Murah
3     Agrowisata, Gianyar, Dekat dari Bandara, Gratis
4     Agrowisata, Tabanan, Sedang dari Bandara, Murah
                           ...                       
70      Religius, Gianyar, Dekat dari Bandara, Gratis
71        Religius, Badung, Dekat dari Bandara, Murah
72      Religius, Gianyar, Sedang dari Bandara, Murah
73        Religius, Badung, Dekat dari Bandara, Mahal
74     Religius, Karangasem, Jauh dari Bandara, Murah
Name: tags, Length: 75, dtype: object


## Tokenizing

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
def remove_tweet_special(text):
    # remove tab, new line, ans back slice
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # remove non ASCII (emoticon, chinese word, .etc)
    text = text.encode('ascii', 'replace').decode('ascii')
    # remove mention, link, hashtag
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())
    # remove incomplete URL
    return text.replace("http://", " ").replace("https://", " ")
                
tag = tag.apply(remove_tweet_special)

#remove number
def remove_number(text):
    return  re.sub(r"\d+", "", text)

tag = tag.apply(remove_number)

#remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans("","",string.punctuation))
tag = tag.apply(remove_punctuation)

#remove whitespace leading & trailing
def remove_whitespace_LT(text):
    return text.strip()

tag = tag.apply(remove_whitespace_LT)

#remove multiple whitespace into single whitespace
def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text)

tag = tag.apply(remove_whitespace_multiple)

# remove single char
def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

tag = tag.apply(remove_singl_char)

# NLTK word rokenize 
def word_tokenize_wrapper(text):
    return word_tokenize(text)

tag_tokens = tag.apply(word_tokenize_wrapper)

print('Tokenizing Result : \n') 
print(tag_tokens.head())
print('\n\n\n')

Tokenizing Result : 

0    [Agrowisata, Gianyar, Dekat, dari, Bandara, Ma...
1    [Agrowisata, Gianyar, Sedang, dari, Bandara, M...
2    [Agrowisata, Denpasar, Dekat, dari, Bandara, M...
3    [Agrowisata, Gianyar, Dekat, dari, Bandara, Gr...
4    [Agrowisata, Tabanan, Sedang, dari, Bandara, M...
Name: tags, dtype: object






In [ ]:
#save data
dataset['category'] = cat
dataset['tags'] = tag
dataset['description'] = desc
dataset

category                                          tags  weekend_price  \
0   Agrowisata   Agrowisata Gianyar Dekat dari Bandara Mahal          50000   
1   Agrowisata  Agrowisata Gianyar Sedang dari Bandara Mahal         300000   
2   Agrowisata  Agrowisata Denpasar Dekat dari Bandara Murah          35000   
3   Agrowisata  Agrowisata Gianyar Dekat dari Bandara Gratis              0   
4   Agrowisata  Agrowisata Tabanan Sedang dari Bandara Murah          40000   
..         ...                                           ...            ...   
70    Religius    Religius Gianyar Dekat dari Bandara Gratis              0   
71    Religius      Religius Badung Dekat dari Bandara Murah          15000   
72    Religius    Religius Gianyar Sedang dari Bandara Murah          30000   
73    Religius      Religius Badung Dekat dari Bandara Mahal          50000   
74    Religius   Religius Karangasem Jauh dari Bandara Murah          25000   

    weekday_price distance  rating            place_name        city  \
0           50000    dekat     3.0     Agrowisata Satria     Gianyar   
1          300000   sedang     5.0      Aloha Ubud Swing     Gianyar   
2           30000    dekat     4.0     Big Garden Corner    Denpasar   
3               0    dekat     4.5   Campuhan Ridge Walk     Gianyar   
4           40000   sedang     4.5  Jatiluwih Green Land     Tabanan   
..            ...      ...     ...                   ...         ...   
70              0    dekat     4.0        Pura Saraswati     Gianyar   
71          15000    dekat     4.0       Pura Taman Ayun      Badung   
72          30000   sedang     4.5      Pura Tirta Empul     Gianyar   
73          50000    dekat     4.0          Pura Uluwatu      Badung   
74          25000     jauh     4.5          Tirta Gangga  Karangasem   

                                                image  \
0   https://drive.google.com/file/d/108VxoEhKsyV2_...   
1   https://drive.google.com/file/d/1bvzte6xbyb6Ey...   
2   https://drive.google.com/file/d/12UMKldf_s7zGI...   
3   https://drive.google.com/file/d/1eVpiUN3lv1uzV...   
4   https://drive.google.com/file/d/1vX9x5gLEmQKdg...   
..                                                ...   
70  https://drive.google.com/file/d/13cUb10qppNS-U...   
71  https://drive.google.com/file/d/1PL_N2I8BD4Ylj...   
72  https://drive.google.com/file/d/1-q6YUrkNSTtiM...   
73  https://drive.google.com/file/d/1-q6YUrkNSTtiM...   
74  https://drive.google.com/file/d/11G0xeW6eAGzd1...   

                                          description  
0   ['agrowisata satria menawarkan 'rasa' bali pad...  
1   ['ajaklah orang-orang tercinta untuk mencoba a...  
2   ['objek wisata big garden corner sanur adalah ...  
3   ['campuhan ridge walk adalah sebuah trek joggi...  
4   ['nominasi untuk penunjukan sebagai situs wari...  
..                                                ...  
70  ['pura saraswati merupakan pura yang didirikan...  
71  ['pura taman ayun di susun dengan konsep taman...  
72  ['tirta empul adalah nama sebuah pura hindu ya...  
73  ['pura yang terletak di ujung barat daya pulau...  
74  ['ada tiga hal utama yang ada di taman tirta g...  

[75 rows x 10 columns]

In [ ]:
dataset.to_csv("wisatabali.csv")

#Recommendation

In [ ]:
# loading the data from the csv file to apandas dataframe
dataset = pd.read_csv("wisatabali.csv").dropna()
dataset.head()

Unnamed: 0    category                                          tags  \
0           0  Agrowisata   Agrowisata Gianyar Dekat dari Bandara Mahal   
1           1  Agrowisata  Agrowisata Gianyar Sedang dari Bandara Mahal   
2           2  Agrowisata  Agrowisata Denpasar Dekat dari Bandara Murah   
3           3  Agrowisata  Agrowisata Gianyar Dekat dari Bandara Gratis   
4           4  Agrowisata  Agrowisata Tabanan Sedang dari Bandara Murah   

   weekend_price  weekday_price distance  rating            place_name  \
0          50000          50000    dekat     3.0     Agrowisata Satria   
1         300000         300000   sedang     5.0      Aloha Ubud Swing   
2          35000          30000    dekat     4.0     Big Garden Corner   
3              0              0    dekat     4.5   Campuhan Ridge Walk   
4          40000          40000   sedang     4.5  Jatiluwih Green Land   

       city                                              image  \
0   Gianyar  https://drive.google.com/file/d/108VxoEhKsyV2_...   
1   Gianyar  https://drive.google.com/file/d/1bvzte6xbyb6Ey...   
2  Denpasar  https://drive.google.com/file/d/12UMKldf_s7zGI...   
3   Gianyar  https://drive.google.com/file/d/1eVpiUN3lv1uzV...   
4   Tabanan  https://drive.google.com/file/d/1vX9x5gLEmQKdg...   

                                         description  
0  ['agrowisata satria menawarkan 'rasa' bali pad...  
1  ['ajaklah orang-orang tercinta untuk mencoba a...  
2  ['objek wisata big garden corner sanur adalah ...  
3  ['campuhan ridge walk adalah sebuah trek joggi...  
4  ['nominasi untuk penunjukan sebagai situs wari...

In [ ]:
def important_features(dataset):
    data=dataset.copy()
    for i in range(0, dataset.shape[0]):
        data["imp"]= data["category"]+" "+data["tags"]
    return data


In [ ]:
data=important_features(dataset)

In [ ]:
data.head()

Unnamed: 0    category                                          tags  \
0           0  Agrowisata   Agrowisata Gianyar Dekat dari Bandara Mahal   
1           1  Agrowisata  Agrowisata Gianyar Sedang dari Bandara Mahal   
2           2  Agrowisata  Agrowisata Denpasar Dekat dari Bandara Murah   
3           3  Agrowisata  Agrowisata Gianyar Dekat dari Bandara Gratis   
4           4  Agrowisata  Agrowisata Tabanan Sedang dari Bandara Murah   

   weekend_price  weekday_price distance  rating            place_name  \
0          50000          50000    dekat     3.0     Agrowisata Satria   
1         300000         300000   sedang     5.0      Aloha Ubud Swing   
2          35000          30000    dekat     4.0     Big Garden Corner   
3              0              0    dekat     4.5   Campuhan Ridge Walk   
4          40000          40000   sedang     4.5  Jatiluwih Green Land   

       city                                              image  \
0   Gianyar  https://drive.google.com/file/d/108VxoEhKsyV2_...   
1   Gianyar  https://drive.google.com/file/d/1bvzte6xbyb6Ey...   
2  Denpasar  https://drive.google.com/file/d/12UMKldf_s7zGI...   
3   Gianyar  https://drive.google.com/file/d/1eVpiUN3lv1uzV...   
4   Tabanan  https://drive.google.com/file/d/1vX9x5gLEmQKdg...   

                                         description  \
0  ['agrowisata satria menawarkan 'rasa' bali pad...   
1  ['ajaklah orang-orang tercinta untuk mencoba a...   
2  ['objek wisata big garden corner sanur adalah ...   
3  ['campuhan ridge walk adalah sebuah trek joggi...   
4  ['nominasi untuk penunjukan sebagai situs wari...   

                                                 imp  
0  Agrowisata Agrowisata Gianyar Dekat dari Banda...  
1  Agrowisata Agrowisata Gianyar Sedang dari Band...  
2  Agrowisata Agrowisata Denpasar Dekat dari Band...  
3  Agrowisata Agrowisata Gianyar Dekat dari Banda...  
4  Agrowisata Agrowisata Tabanan Sedang dari Band...

In [ ]:
data["ids"]=[i for i in range(0,data.shape[0])]

##Importing vectoriser

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
vec=TfidfVectorizer()

In [ ]:
vecs=vec.fit_transform(data["imp"].apply(lambda x: np.str_(x)))

In [ ]:
vecs.shape

(75, 22)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
sim=cosine_similarity(vecs) 
print(sim)

[[1.         0.94080748 0.74973552 ... 0.14489381 0.22954495 0.03596026]
 [0.94080748 1.         0.69742859 ... 0.23535769 0.18249954 0.03517785]
 [0.74973552 0.69742859 1.         ... 0.09844467 0.0801377  0.0857113 ]
 ...
 [0.14489381 0.23535769 0.09844467 ... 1.         0.68465895 0.67118511]
 [0.22954495 0.18249954 0.0801377  ... 0.68465895 1.         0.59610147]
 [0.03596026 0.03517785 0.0857113  ... 0.67118511 0.59610147 1.        ]]


In [ ]:
sim.shape##Columns represnt movie-ids and not rows

(75, 75)

In [ ]:
sim[0][74]

0.03596026028903452

In [ ]:
def recommend(place):
    place_id=data[data.category==place]["ids"].values[0]
    scores=list(enumerate(sim[place_id]))
    sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
    sorted_scores=sorted_scores[0:5]
    place=[data[place[0]==data["ids"]]["place_name"].values[0] for place in sorted_scores]
    return place

In [ ]:
def recommend_ten(place_list):
    first_five=[]
    count=0
    for place in place_list:
        if count > 4:
            break
        count+=1
        first_five.append(place)
    return first_five



In [ ]:
categ = input('Enter your category : ')
lst=recommend(categ)
m=recommend_ten(lst)
m

Enter your category : Alam


['Wisata Air Panas Toya Bungkah',
 'Air Terjun Tukad Cepung',
 'Danau Batur',
 'Gunung Batur',
 'Bukit Wanagiri']

##save data

In [ ]:
# Save dataframe
pickle.dump(data.to_dict(), open('rec_wisata.pkl', 'wb'))

In [ ]:
# Save similarity
pickle.dump(sim, open('similarity.pkl', 'wb'))